package at.posselt.pfrpg2e.kingdom.sheet

import at.posselt.pfrpg2e.kingdom.data.RawQuest
import at.posselt.pfrpg2e.kingdom.data.RawQuestRewards

/**
 * Quests that ship with the module and seed every newly created kingdom's quest board.
 *
 * These are Kingmaker companion/roleplay and side quests that don't fit the explore/claim/build
 * hex flow, so they use the "other" type. Ids are stable (not timestamp-based like
 * GM-authored quests) so a seed quest stays identifiable across saves. Content is sourced
 * from the PF2e Kingmaker / Companion Guide material.
 */
fun defaultQuests(): Array<RawQuest> = arrayOf(
    RawQuest(
        id = "naming-ekundayos-dog",
        title = "Naming Ekundayo's Dog",
        description = """Ekundayo refuses to name the anxious dog he rescued, calling it simply "Dog": "Once you name something, the loss you feel when it's inevitably slain makes it not worth naming in the first place. The dog's a tool, not a friend." Once he is at least friendly toward the party, the PCs can convince him to let them name the dog. The final name should be one the players agree on.""",
        giver = "Ekundayo",
        status = "active",
        type = "other",
        rewards = RawQuestRewards(
            xp = 10,
            other = "+1 Influence with Ekundayo",
        ),
        flavorTextCompleted = "A name is decided, and Ekundayo rewards the party with the very briefest of smiles.",
        notes = """Triggers after Ekundayo reaches 2nd level and takes the ranger feat that makes the rescued dog his animal companion; the naming event also requires his attitude toward the party to be at least friendly. A successful Sense Motive reveals his refusal is fear of loss and past trauma, not cruelty.""",
        hidden = false,
    ),
    RawQuest(
        id = "meeting-nok-nok",
        title = "Meeting Nok-Nok",
        description = """Nok-Nok, an Irongut goblin who survived the destruction of his village and fancies himself a legend in the making, latches on to the party as "adventuring heroes" to prove himself. The PCs should first meet him while exploring the Stolen Lands before they take on the Stag Lord: either have him bravely (but not quite arrogantly) wander into their camp with a "friendly" grin shortly after a harrowing fight, or rescue him from the Stag Lord's fort, where the bandits were planning to feed him to the owlbear that very night. He proclaims himself a great goblin hero ready to help kill monsters, promises he won't kill friends, and asks to be friends with each of the PCs.""",
        giver = "Nok-Nok",
        status = "active",
        type = "other",
        rewards = RawQuestRewards(
            other = "Recruit Nok-Nok, an Irongut goblin companion",
        ),
        flavorTextCompleted = "Nok-Nok has decided the party are his heroes-in-the-making — for better or worse, the goblin is one of the band now.",
        notes = """Recruiting him takes almost no effort — he recruits himself. If the PCs attack him he flees but doesn't give up; he keeps showing up regularly until they either kill him or accept his offer of help, and may try to win their favor by saving them from a disastrous encounter or rescuing them if captured. He starts Indifferent and won't obey orders in combat until Influence 4 (Friendly). His goal is to become the fifth goblin hero-god — he worships Lamashtu transactionally — so expect violence, theft, irreverence, and cries of "Blood for Lamashtu!" until rising Influence shifts his alignment.""",
        hidden = false,
    ),
    RawQuest(
        id = "to-ask-for-forgiveness",
        title = "To Ask for Forgiveness",
        description = """Linzi has secretly skimmed money here and there from the kingdom's resources to fund a massive printing press for the new nation. Her plan hits a snag when the crucial parts for the press languish in the hags' hidden enclave alongside her captured Pitaxian mentor, Eobald. The party must track down the missing shipment, confront the Jaggedbriar Coven, and retrieve the press components.""",
        giver = "Linzi",
        status = "active",
        type = "other",
        rewards = RawQuestRewards(
            other = "Linzi becomes Helpful; unlocks the unique printing house structure in the kingdom",
        ),
        flavorTextCompleted = "Eobald is freed and the press parts recovered — Linzi can finally build her printing house.",
        notes = """Triggers soon after the PCs establish their kingdom. On success Linzi becomes Helpful (if she wasn't already) and the party unlocks the printing house structure.""",
        hidden = false,
    ),
    RawQuest(
        id = "blood-calling",
        title = "Blood Calling",
        description = """Amiri approaches the party to seek out the Six Bears and confront them after hearing that her former clan has fled into the Stolen Lands. She secretly wants to ensure her old friend Nilak is safe from the evil spirit and his undead minions hunting the tribe. The party must intervene and help Amiri figure out how to break the ancient curse tied to her oversized frost giant sword.""",
        giver = "Amiri",
        status = "active",
        type = "other",
        level = 11,
        rewards = RawQuestRewards(
            other = "Amiri's loyalty is solidified — she knows she's found her true family and remains a devoted companion",
        ),
        flavorTextCompleted = "The Six Bears are saved and Amiri makes peace with her past.",
        notes = """Occurs as the PCs are about to reach 11th level, around the aftermath of the attack on Tatzlford.""",
        hidden = false,
    ),
    RawQuest(
        id = "the-inconsequent-debates",
        title = "The Inconsequent Debates",
        description = """Jubilost wants to win the Inconsequent Debates, a mythical fey contest to test mortals and reward them for their participation and victory. He asks the party to help track down the ghost of missing gnome explorer Xae to secure an invitation, then travel to the First World border to compete by answering riddles or using skills to trick, intimidate, or entertain the mercurial Host.""",
        giver = "Jubilost Narthropple",
        status = "active",
        type = "other",
        level = 8,
        rewards = RawQuestRewards(
            other = "The contest's winner gets one question answered by the Host; Jubilost learns why the gnomes first left the First World",
        ),
        flavorTextCompleted = "The Host's question is won, and Jubilost finally learns the tragic lore he sought.",
        notes = """Best run at 8th level, just after the events of Chapter 5 resolve but before the Varnhold Vanishing occurs.""",
        hidden = false,
    ),
    RawQuest(
        id = "sir-frederos-challenge",
        title = "Sir Fredero's Challenge",
        description = """Sir Fredero Sinnet sends an arrogant message to his former pupil Valerie, challenging her to a duel at the Shrine of the Golden Grove to answer for her blasphemy against Shelyn. Valerie asks the party to travel with her to meet him, where they soon discover that Sir Fredero is unknowingly being manipulated by a wicked green hag named Tulvak.""",
        giver = "Valerie",
        status = "active",
        type = "other",
        level = 9,
        rewards = RawQuestRewards(
            other = "Valerie gains closure; if the PCs restore the ruined site into a functional shrine, Shelyn grants a character a one-time boon: once, when they roll a failure on a Diplomacy check, they get a critical success instead",
        ),
        flavorTextCompleted = "Valerie gets her closure and the green hag's manipulation is exposed.",
        notes = """A raven messenger delivers Sir Fredero's letter to the capital when the PCs are 9th level, while they are investigating the Varnhold vanishing. Sir Fredero is being manipulated by the green hag Tulvak.""",
        hidden = false,
    ),
    RawQuest(
        id = "defeating-nargloom",
        title = "Defeating Nargloom",
        description = """Nok-Nok learns that the Tanglethorn goblins have returned and their new leader is planning to raid Oleg's Trading Post to reassert Tanglethorn dominance over the region. He asks the party to help him intervene so he can prove his heroism to Lamashtu by challenging and defeating one of her chosen agents — the barghest Nargloom.""",
        giver = "Nok-Nok",
        status = "active",
        type = "other",
        level = 5,
        rewards = RawQuestRewards(
            other = "Several potions (including two invisibility potions); turning Nargloom's journals over to the mayor of Nivakta's Crossing grants the kingdom two bonus Resource Dice at the start of the next turn",
        ),
        flavorTextCompleted = "Nargloom is slain and the Tanglethorn raid broken — Nok-Nok has his heroic deed.",
        notes = """Occurs when the PCs reach 5th level, ideally in a lull before the Beast attacks their capital city.""",
        hidden = false,
    ),
    RawQuest(
        id = "a-missing-brother",
        title = "A Missing Brother",
        description = """Edrist Hanvaki is sick with worry over his brother Temin, who recently traveled to Varnhold to seal a deal with that village's gem cutter and then vanished. The party must search the hills for buzzards to locate Temin's remains and piece together his doom.""",
        giver = "Edrist Hanvaki",
        status = "active",
        type = "other",
        rewards = RawQuestRewards(
            xp = 30,
            other = "75 gp from Edrist for bringing him the brooch or the news he seeks",
        ),
        flavorTextCompleted = "Temin's fate is uncovered and the news brought back to a grieving Edrist.",
        notes = """Edrist approaches the party for help in the month after the first Kingdom turn is completed.""",
        hidden = false,
    ),
    RawQuest(
        id = "a-ladys-desire",
        title = "A Lady's Desire",
        description = """Lady Lily Teskertin has long wished to own a piece of fine elven art after hearing rumors of a ruin in the southern Narlmarches. The party must travel to the Forgotten Keep and salvage a piece of fine elven artistry to bring back as a prize.""",
        giver = "Lady Lily Teskertin",
        status = "active",
        type = "other",
        rewards = RawQuestRewards(
            xp = 30,
            other = "Lady Lily's dead father's old diplomat's badge in return for the statue",
        ),
        flavorTextCompleted = "The elven statue is recovered and presented to Lady Lily.",
        notes = """Lily approaches the PCs after they build their first Manor or attempt Craft Luxuries for the first time, or if word spreads that they've started exploring the Forgotten Keep.""",
        hidden = false,
    ),
    RawQuest(
        id = "the-omelet-king",
        title = "The Omelet King",
        description = """The quirky chef Jamery Gerbasken announces a desire to cook an enormous omelet from a single roc's egg. The PCs must hunt down a massive, intact roc egg (such as those found at the Isle of the Lizard King) and deliver it to him so he can organize a huge omelet-cooking competition.""",
        giver = "Jamery Gerbasken",
        status = "active",
        type = "other",
        level = 9,
        rewards = RawQuestRewards(
            xp = 30,
            other = """A free Luxury Tavern, "The Roc's Nest," that the PCs can place in any settlement during the Civic Activities step""",
        ),
        flavorTextCompleted = "The roc's egg is delivered and the great omelet-cooking competition is on.",
        notes = """Jamery approaches the party once the kingdom reaches 9th level.""",
        hidden = false,
    ),
    RawQuest(
        id = "wanted-manticore",
        title = "Wanted: Manticore",
        description = """The eccentric local poet Iosis Vemarelian wants to write a complex epic using only pens crafted from manticore spikes. The party must track down manticores in the wild and successfully harvest a healthy collection of spikes from the carcasses using the Survival skill.""",
        giver = "Iosis Vemarelian",
        status = "active",
        type = "other",
        level = 6,
        rewards = RawQuestRewards(
            xp = 30,
            other = "A rare book of halfling poetry worth 200 gp",
        ),
        flavorTextCompleted = "A fresh bundle of manticore spikes is delivered to Iosis.",
        notes = """Iosis posts wanted-board requests once the PCs reach 6th level.""",
        hidden = false,
    ),
    RawQuest(
        id = "the-mammoths-shame",
        title = "The Mammoth's Shame",
        description = """An elderly, intelligent mammoth named Hillstomper approaches the party with a pronounced limp and a plea for aid, explaining that he's been charged with guarding the mammoth graveyard in the mountain foothills. The party must help him reclaim the holy site by killing the two cairn linnorms that have claimed the place as their new den.""",
        giver = "Hillstomper",
        status = "active",
        type = "other",
        rewards = RawQuestRewards(
            xp = 30,
            other = "30 Kingdom XP; the PCs may incorporate the graveyard into their kingdom, automatically Claiming the hex on a critical success",
        ),
        flavorTextCompleted = "The cairn linnorms are slain and the mammoth graveyard restored to Hillstomper's keeping.",
        notes = """Found by speaking to Hillstomper during hexploration.""",
        hidden = false,
    ),
    // --- Chapter 4: Rivers Run Red (Kingdom Events & Quests, pp. 184-213) ---
    RawQuest(
        id = "ch4-the-slain-townsfolk",
        title = "The Slain Townsfolk",
        description = """Citizens are savaged in the night just outside a settlement, sparking rumors that a "maneater" stalks the hinterlands. Two villagers — Saki and Beven — are slaughtered on consecutive nights. Investigating the bodies and kill sites (Medicine, Nature, or Survival) reveals a wolf-like beast and barefoot human tracks leading back into town — to Kundal, a newly arrived trapper who drinks himself to sleep each night to escape his nightmares, unaware he is an afflicted werewolf.""",
        giver = "Kundal",
        status = "active",
        type = "other",
        rewards = RawQuestRewards(
            other = "Resolving the killings stabilizes the settlement; failing to stop Kundal increases Unrest as he claims a third victim",
        ),
        flavorTextCompleted = "The killings stop and the town's panic subsides once Kundal's curse is dealt with.",
        notes = """Chapter 4 Kingdom Event — EVENT 1, Severe 4 (pp. 188-191). Time it to take place just before the last day of the full moon. The perpetrator is the werewolf trapper Kundal.""",
        hidden = false,
    ),
    RawQuest(
        id = "ch4-the-rabble-rouser",
        title = "The Rabble-Rouser",
        description = """A charismatic orator arrives in the capital while the PCs are adventuring and begins giving speeches criticizing and denigrating their leadership. He is secretly a Pitaxian spy seeking to undermine the PCs' authority, and the rulers must deal with him — by force, bribery, or a fair trial — before he escalates the kingdom's Unrest.""",
        giver = "Grigori",
        status = "active",
        type = "other",
        rewards = RawQuestRewards(
            other = "30 Kingdom XP (increased to 80 if he is given a fair, public trial); the PCs earn combat XP whether they defeat him in battle or through rhetoric",
        ),
        flavorTextCompleted = "Grigori is silenced or exposed, and the crowd's discontent fades.",
        notes = """Chapter 4 Kingdom Event — EVENT 2, Severe 4 (pp. 191-194). Grigori is a Pitaxian bard and spy.""",
        hidden = false,
    ),
    RawQuest(
        id = "ch4-desperate-spies",
        title = "Desperate Spies",
        description = """As the troll king Hargulka expands his power, he sends two captured kobolds to spy on the PCs' kingdom. The pair tries to learn what they can without getting caught, motivated by the fact that their fear of Hargulka is slightly greater than their fear of adventurers and big cities.""",
        giver = "Kereek & Prazil",
        status = "active",
        type = "other",
        rewards = RawQuestRewards(
            other = "Defeating them yields a dagger, robes, a wand of burning hands, a breastplate, a +1 silver warhammer, and a steel shield",
        ),
        flavorTextCompleted = "The kobold spies are caught or driven off before they can report back to Hargulka.",
        notes = """Chapter 4 Kingdom Event — EVENT 3, Severe 4 (pp. 194-195). The spies, Kereek and Prazil, were sent by King Hargulka.""",
        hidden = false,
    ),
    RawQuest(
        id = "ch4-the-cult-of-gyronna",
        title = "The Cult of Gyronna",
        description = """A sinister cult devoted to the hag-goddess Gyronna infiltrates the capital, led by a respected midwife. Malgorzata "Goody" Niska uses her trusted position to recruit outcasts and steal newborn babies, replacing them with changelings, before her flock can set the townsfolk at each other's throats.""",
        giver = "Goody Niska",
        status = "active",
        type = "other",
        rewards = RawQuestRewards(
            other = "A fist-sized cat's-eye chrysoberyl worth 50 gp, and a plain wooden coffer holding 100 gp and a secret note from the Black Tears mercenaries",
        ),
        flavorTextCompleted = "Goody Niska's cult is rooted out before it can turn the capital against itself.",
        notes = """Chapter 4 Kingdom Event — EVENT 4, Severe 4 (pp. 196-197). The cult is led by the midwife and cleric of Gyronna, Malgorzata "Goody" Niska.""",
        hidden = false,
    ),
    RawQuest(
        id = "ch4-the-founding-of-tatzlford",
        title = "The Founding of Tatzlford",
        description = """Loy and Latricia Rezbin, a ruddy, friendly, and energetic couple, approach the PCs with plans to establish a new village. They ask for support getting their settlement started deep in the Narlmarches, at a river ford where a pair of tatzlwyrms dwelled.""",
        giver = "Loy & Latricia Rezbin",
        status = "active",
        type = "other",
        rewards = RawQuestRewards(
            other = "30 Kingdom XP; on a success Tatzlford is founded, claimed, and automatically integrated into the kingdom as a village with several free structures (houses, inn, town hall)",
        ),
        flavorTextCompleted = "Tatzlford is founded and woven into the young kingdom.",
        notes = """Chapter 4 minor Kingdom Event — Beneficial Event +0 (p. 198). Given by Loy and Latricia Rezbin.""",
        hidden = false,
    ),
    RawQuest(
        id = "ch4-return-of-the-black-tears",
        title = "Return of the Black Tears",
        description = """Following their defeat at Lady Jamandi's manor, the surviving Black Tears mercenaries seek revenge as the PCs' nation grows. They make their presence known by attempting a very public attack on the kingdom to send a clear message: the Black Tears do not forget. The PCs must use the Intrigue skill to thwart their vandalism and murder attempts.""",
        giver = "Black Tears mercenaries",
        status = "active",
        type = "other",
        rewards = RawQuestRewards(
            other = "30 Kingdom XP; a critical success reduces the kingdom's Unrest by 1d4",
        ),
        flavorTextCompleted = "The Black Tears' campaign of revenge is broken before it can take root.",
        notes = """Chapter 4 minor Kingdom Event — Dangerous Event +0 (p. 198).""",
        hidden = false,
    ),
    RawQuest(
        id = "ch4-troll-sightings",
        title = "Troll Sightings",
        description = """Reports of trolls begin filtering in from the kingdom's frontier as Hargulka's monster realm stirs. The ongoing sightings unsettle the populace and set the stage for the trolls' raids — the prelude that leads into the Troll Slaying quest.""",
        giver = "Kingdom scouts",
        status = "active",
        type = "other",
        rewards = RawQuestRewards(
            other = "An ongoing Dangerous event; left unchecked it builds toward Hargulka's raids (see the Troll Slaying quest)",
        ),
        flavorTextCompleted = "The scattered sightings resolve into a clear picture of the gathering troll threat.",
        notes = """Chapter 4 minor Kingdom Event — Dangerous Event +0, Ongoing (p. 199). Sets up the Troll Slaying quest.""",
        hidden = false,
    ),
    RawQuest(
        id = "ch4-trouble-with-a-weird-gnome",
        title = "Trouble with a Weird Gnome",
        description = """Strange rumors spread of a weird gnome with bright orange hair and glowing eyes causing isolated fires, missing tools, and unsettling pranks. Unbeknownst to the citizens, this gnome is a mischievous manifestation of the Lantern King himself, come to the Stolen Lands to size up the PCs' kingdom.""",
        giver = "The Lantern King",
        status = "active",
        type = "other",
        rewards = RawQuestRewards(
            other = "30 Kingdom XP; on a critical success the investigators uncover his fey nature, soothing the citizens and decreasing Unrest by 1",
        ),
        flavorTextCompleted = "The prankster's fey nature is uncovered, soothing the worried citizens.",
        notes = """Chapter 4 minor Kingdom Event — Dangerous Event +0 (p. 199). The "weird gnome" is the Lantern King.""",
        hidden = false,
    ),
    RawQuest(
        id = "ch4-troll-slaying",
        title = "Troll Slaying",
        description = """Trolls led by the ambitious Hargulka have begun forming a monster kingdom, leading raids and leaving ripples of discord and terror in their wake. The terrified citizens demand the PCs step in to defeat Hargulka's trolls and end the giant threat.""",
        giver = "Residents of the kingdom",
        status = "active",
        type = "other",
        rewards = RawQuestRewards(
            other = "80 Kingdom XP; Hargulka's death reduces Unrest by 2d6 and grants 3 bonus Fame/Infamy at the start of the next Kingdom turn. The trolls' fortress holds varied treasure, including a clear spindle aeon stone",
        ),
        flavorTextCompleted = "Hargulka falls and the citizens rejoice; the troll kingdom is broken.",
        notes = """Chapter 4 Quest — 80 Kingdom XP (pp. 200-201). Preceded by the Troll Sightings event; the trolls are led by King Hargulka.""",
        hidden = false,
    ),
    RawQuest(
        id = "ch4-hunting-the-beast",
        title = "Hunting the Beast",
        description = """An immense owlbear, driven to a furious rage, attacks civilization — tearing up newly plowed fields and leaving buildings and structures in shambles. The kingdom's citizens demand the PCs hunt down and slay the Beast to restore peace to their borders.""",
        giver = "Residents of the kingdom",
        status = "active",
        type = "other",
        rewards = RawQuestRewards(
            other = "80 Kingdom XP; slaying the Beast reduces Unrest by 2d6, grants 3 bonus Fame/Infamy at the start of the next turn, and lets its lair serve as a Refuge if the hex is claimed",
        ),
        flavorTextCompleted = "The Beast is slain and peace returns to the kingdom's borders.",
        notes = """Chapter 4 Quest — 80 Kingdom XP (pp. 208-209). The Beast's initial attack is handled by the "Rampage of the Beast" event (Dangerous +4, Settlement, p. 209).""",
        hidden = false,
    ),
    // --- Companion recruitment (Companion Guide) ---
    RawQuest(
        id = "meeting-kalikke-kanerah",
        title = "Meeting Kalikke & Kanerah",
        description = """The PCs shouldn't meet one of the tiefling sisters until after they've established their kingdom, and which sister appears depends on the kingdom's reputation: Kalikke first if the kingdom is Famous, Kanerah if it is Infamous. As Kalikke, she is a shy woman who approaches hoping for permission to establish a modest academy for studying elemental magic; as Kanerah, she is a criminal brought before the PCs to face punishment for minor crimes. The two share one body — after Kanerah was executed in their youth, Kalikke made a deal with a balor called the Forefather to bring her back, but he bound them so that Kanerah can only exist when Kalikke does not.""",
        giver = "Kalikke & Kanerah",
        status = "active",
        type = "other",
        level = 5,
        rewards = RawQuestRewards(
            other = "Recruit Kalikke/Kanerah (tiefling kineticist companion); rising Influence unlocks leadership roles — Kalikke as Counselor, Kanerah as Emissary",
        ),
        flavorTextCompleted = "One sister steps into the party's service — only ever one at a time, but the twins are theirs now.",
        notes = """Companion Guide (p. 98). Met only after the kingdom is established; Famous kingdom → Kalikke, Infamous → Kanerah. Kalikke (Chaotic Good) is the dominant, soft-spoken personality; under distress she becomes Kanerah (Lawful Evil), quick-tempered and rash. Influence ladder: 4 → Friendly (10 XP, aids camping, Kalikke as Counselor / Kanerah as Emissary); 6 → Helpful (shares aqueous blast via Kalikke or scorching blast via Kanerah); 8 → admits the cursed truth (30 XP, shares the other spell, and can shift between sisters as the PCs direct during daily preparations).""",
        hidden = false,
    ),
    RawQuest(
        id = "meeting-octavia-regongar",
        title = "Meeting Octavia & Regongar",
        description = """The PCs meet the wizard Octavia and the magus Regongar together after completing Part 1 of Chapter 3 of the Kingmaker Adventure Path. The pair can stumble across the PCs' campsite, bedraggled and exhausted after escaping the Technic League only days before, or the PCs can stumble across a group of Technic League bounty hunters and be the means by which the two escape their clutches. Octavia is desperate and frightened but, as long as the PCs are friendly and welcoming, relatively easy to win over; Regongar starts Unfriendly and trusts no one but Octavia, yet accompanies her wherever she goes.""",
        giver = "Octavia & Regongar",
        status = "active",
        type = "other",
        level = 6,
        rewards = RawQuestRewards(
            other = "Recruit Octavia and Regongar (wizard/rogue and magus); rising Influence unlocks leadership roles — Octavia as Magister, Regongar as General",
        ),
        flavorTextCompleted = "Octavia and Regongar throw in with the party — win her over, and the magus follows.",
        notes = """Companion Guide (pp. 102 & 104). Met after Part 1 of Chapter 3 (campsite escape or rescue from Technic League bounty hunters). Octavia (Chaotic Good) starts Indifferent and is easy to recruit if welcomed; Regongar (Chaotic Evil) starts Unfriendly but follows Octavia, keeping his violence to the PCs' enemies while she stays allied. Octavia: Influence 2 → Friendly (10 XP), 4 → Helpful (vision of beauty at 3rd level), 6 → Magister (30 XP). Regongar: 2 → Indifferent, 4 → Friendly (10 XP, follows battle orders), 6 → Helpful (energy-absorbing armor rune at 11th level), 8 → General (30 XP).""",
        hidden = false,
    ),
)
